#!/usr/bin/env python3
"""Regenerate src/unicode_tables.rs from the running CPython's Unicode data.

Dev-time only (not needed to build devcap). Usage:
    python3 scripts/gen_unicode_tables.py > src/unicode_tables.rs && cargo fmt
"""
import sys, unicodedata
def ranges(pred):
    out=[]; start=None
    for cp in range(0x110000):
        c=chr(cp)
        ok = pred(c)
        if ok and start is None: start=cp
        if not ok and start is not None: out.append((start,cp-1)); start=None
    if start is not None: out.append((start,0x10FFFF))
    return out
def emit(name, rs):
    s=f"pub(crate) static {name}: &[(u32, u32)] = &[\n"
    for a,b in rs: s+=f"    (0x{a:X}, 0x{b:X}),\n"
    return s+"];\n\n"
dec = ranges(lambda c: c.isdecimal())
for a,b in dec:
    for cp in range(a,b+1):
        assert (cp-a)%10 == unicodedata.decimal(chr(cp)), hex(cp)
out = "// @generated by scripts/gen_unicode_tables.py from CPython %s (Unicode %s).\n// Do not edit by hand.\n\n" % (sys.version.split()[0], unicodedata.unidata_version)
out += "/// `str.isdecimal()` ranges; each range starts at a digit zero.\n" + emit("DECIMAL", dec)
out += "/// `str.isalnum()` ranges (non-ASCII part used for regex `\\w`).\n" + emit("ALNUM", ranges(lambda c: c.isalnum()))
out += "/// `str.isspace()` ranges.\n" + emit("SPACE", ranges(lambda c: c.isspace()))
out += "/// `str.isprintable()` ranges (used by `repr`).\n" + emit("PRINTABLE", ranges(lambda c: c.isprintable()))
sys.stdout.write(out)
